### ISSUE TITLE
win_domain_user: handle user name with spaces

### ISSUE THREAD

**Issue by Harliff** [ansible-collections/community.windows#360]
##### SUMMARY

If "name" is contained a space, then win_domain_user tries to create it again. 
(Yes - we're using full user name (lastname + firstname + middlename) as CN while keeping shortnames only as UPN).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_domain_user

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /home/harliff/.ansible.cfg
  configured module search path = ['/home/harliff/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.3.0  

# /home/harliff/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.windows 1.1.0  

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/harliff/.ansible.cfg) = ['/home/harliff/ansible/ak.inventory']
DEFAULT_STDOUT_CALLBACK(/home/harliff/.ansible.cfg) = debug
DEPRECATION_WARNINGS(/home/harliff/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/harliff/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Host: Debian 11.2
AD on Windows server 2016

##### STEPS TO REPRODUCE

Use the playbook with task (see bellow) on an AD controller **twice**

```yaml
    - name: ensure test user exist
      win_domain_user:
        name: Test user
        upn: testuser@az-ka.ru
        password: "{{user_password}}"
        path: "{{OU_path_users}}"
```

##### EXPECTED RESULTS

On first run - the user is created
On second run - nothing changed (due to idempotentcy).

##### ACTUAL RESULTS

On first run - the user is created
On second run - error raised:

```paste below
TASK [ensure test user exist] ***************************************************************************************
task path: /home/harliff/ansible/dev-ad-new-user.yml:91
redirecting (type: modules) ansible.builtin.win_domain_user to community.windows.win_domain_user
Using module file /home/harliff/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_user.ps1
Pipelining is enabled.
<ad-server.example.org> ESTABLISH WINRM CONNECTION FOR USER: admin@example.org on PORT 5986 TO ad-server.example.org
EXEC (via pipeline wrapper)
The full traceback is:
The specified account already exists
At line:165 char:21
+ ... $user_obj = New-ADUser @create_args -WhatIf:$check_mode -PassThru @ex ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (CN=Test user,OU...C=example,DC=org:String) [New-ADUser], ADIdentityAlreadyExistsException
    + FullyQualifiedErrorId : ActiveDirectoryServer:1316,Microsoft.ActiveDirectory.Management.Commands.NewADUser

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 165

Microsoft.ActiveDirectory.Management.ADIdentityAlreadyExistsException: The specified account already exists ---> System.ServiceModel.FaultException: The supplied entry already exists.
   --- End of inner exception stack trace ---
   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForExtendedError(String extendedErrorMessage, Exception innerException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForErrorCode(String message, String errorCode, String extendedErrorMessage, Exception innerException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForFaultDetail(FaultDetail faultDetail, FaultException faultException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowException(AdwsFault adwsFault, FaultException faultException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.Create(ADAddRequest request)
   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperations.Add(ADSessionHandle handle, ADAddRequest request)
   at Microsoft.ActiveDirectory.Management.ADActiveObject.Create()
   at Microsoft.ActiveDirectory.Management.Commands.ADNewCmdletBase`3.ADNewCmdletBaseProcessCSRoutine()
   at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.ProcessRecord()
fatal: [ad-server.example.org]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: The specified account already exists"
}
```

**Comment by jborean93** [comment]
The `win_domain_user` module has been deprecated by https://github.com/ansible-collections/community.windows/pull/516 in favour of [microsoft.ad.user](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/user_module.html#ansible-collections-microsoft-ad-user-module). See the [migration guide](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/docsite/guide_migration.html#module-win-domain-user) for more info on how to change your code to use the newer module.

The `microsoft.ad.user` module operates by having `name` being the LDAP object name which will fix this problem here.
